#! /bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SRC_ASSETS_DIR=src
SRC_PROJECT_SETTINGS_DIR="$SCRIPT_DIR/ProjectSettings"

DST_ASSETS_DIR=./Project/Assets
DST_PROJECT_SETTINGS_DIR=./Project/ProjectSettings
TARGET_PROJECT_SETTINGS_DIR

mkdir -p $DST_ASSETS_DIR
mkdir -p $DST_PROJECT_SETTINGS_DIR

cp -r $SRC_ASSETS_DIR $DST_ASSETS_DIR
echo "Copied $SRC_ASSETS_DIR to $DST_ASSETS_DIR"
cp -r $SRC_PROJECT_SETTINGS_DIR $DST_PROJECT_SETTINGS_DIR
echo "Copied $SRC_PROJECT_SETTINGS_DIR to $DST_PROJECT_SETTINGS_DIR"
